"""B站 MPI 报表字段定义（按 B站开放平台文档字段名展示）。"""

BILI_COLUMN_CATEGORIES = [
    {"id": "dimension", "label": "维度字段", "icon": "bi-diagram-3"},
    {"id": "basic", "label": "基础数据", "icon": "bi-bar-chart"},
    {"id": "launch", "label": "投放消耗", "icon": "bi-cash-coin"},
    {"id": "video", "label": "视频互动", "icon": "bi-play-circle"},
    {"id": "campaign", "label": "计划字段", "icon": "bi-megaphone"},
    {"id": "unit", "label": "单元字段", "icon": "bi-bounding-box"},
    {"id": "creative", "label": "创意字段", "icon": "bi-palette"},
    {"id": "clue", "label": "销售线索", "icon": "bi-person-lines-fill"},
    {"id": "app", "label": "应用与游戏", "icon": "bi-phone"},
    {"id": "ecommerce", "label": "电商店铺", "icon": "bi-shop"},
    {"id": "live", "label": "直播间", "icon": "bi-broadcast"},
    {"id": "star", "label": "星任务数据", "icon": "bi-star"},
    {"id": "jinghuo", "label": "京火数据", "icon": "bi-fire"},
    {"id": "grass", "label": "种草数据", "icon": "bi-flower1"},
]

BILI_ALL_COLUMNS = [
    {"key": "time", "label": "日期", "category": "dimension", "format": "text", "default": True, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "skip"},
    {"key": "date_time", "label": "小时", "category": "dimension", "format": "text", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "skip"},
    {"key": "_account_name", "label": "B站账号名称", "category": "dimension", "format": "text", "default": True, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "skip"},
    {"key": "account_id", "label": "广告主账户ID", "category": "dimension", "format": "text", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "skip"},

    {"key": "campaign_id", "label": "计划ID", "category": "campaign", "format": "text", "default": True, "level": ["campaign", "unit", "creativity"], "aggregate": "skip"},
    {"key": "campaign_name", "label": "计划名称", "category": "campaign", "format": "text", "default": True, "level": ["campaign", "unit", "creativity"], "aggregate": "skip"},
    {"key": "campaign_status", "label": "计划状态", "category": "campaign", "format": "text", "default": False, "level": ["campaign", "unit", "creativity"], "aggregate": "skip"},
    {"key": "ad_type", "label": "广告类型", "category": "campaign", "format": "text", "default": False, "level": ["campaign", "unit", "creativity"], "aggregate": "skip"},
    {"key": "promotion_purpose_type", "label": "推广目的", "category": "campaign", "format": "text", "default": False, "level": ["campaign", "unit", "creativity"], "aggregate": "skip"},
    {"key": "support_auto", "label": "是否支持自动托管", "category": "campaign", "format": "text", "default": False, "level": ["campaign", "unit", "creativity"], "aggregate": "skip"},
    {"key": "campaign_budget", "label": "计划预算", "category": "campaign", "format": "money", "default": False, "level": ["campaign", "unit", "creativity"], "aggregate": "skip"},
    {"key": "campaign_ctime", "label": "计划创建时间", "category": "campaign", "format": "text", "default": False, "level": ["campaign", "unit", "creativity"], "aggregate": "skip"},
    {"key": "campaign_mtime", "label": "计划更新时间", "category": "campaign", "format": "text", "default": False, "level": ["campaign", "unit", "creativity"], "aggregate": "skip"},

    {"key": "unit_id", "label": "单元ID", "category": "unit", "format": "text", "default": True, "level": ["unit", "creativity"], "aggregate": "skip"},
    {"key": "unit_name", "label": "单元名称", "category": "unit", "format": "text", "default": True, "level": ["unit", "creativity"], "aggregate": "skip"},
    {"key": "unit_status", "label": "单元状态", "category": "unit", "format": "text", "default": False, "level": ["unit", "creativity"], "aggregate": "skip"},
    {"key": "status", "label": "启停状态", "category": "unit", "format": "text", "default": False, "level": ["unit", "creativity"], "aggregate": "skip"},
    {"key": "sales_mode", "label": "售卖模式", "category": "unit", "format": "text", "default": False, "level": ["unit", "creativity"], "aggregate": "skip"},
    {"key": "unit_budget", "label": "单元预算", "category": "unit", "format": "money", "default": False, "level": ["unit", "creativity"], "aggregate": "skip"},
    {"key": "launch_begin_date", "label": "投放开始日期", "category": "unit", "format": "text", "default": False, "level": ["unit", "creativity"], "aggregate": "skip"},
    {"key": "launch_end_date", "label": "投放结束日期", "category": "unit", "format": "text", "default": False, "level": ["unit", "creativity"], "aggregate": "skip"},
    {"key": "launch_time", "label": "投放时段", "category": "unit", "format": "text", "default": False, "level": ["unit", "creativity"], "aggregate": "skip"},
    {"key": "target", "label": "定向信息", "category": "unit", "format": "text", "default": False, "level": ["unit", "creativity"], "aggregate": "skip"},

    {"key": "creative_id", "label": "创意ID", "category": "creative", "format": "text", "default": True, "level": ["creativity"], "aggregate": "skip"},
    {"key": "creative_name", "label": "创意名称", "category": "creative", "format": "text", "default": True, "level": ["creativity"], "aggregate": "skip"},
    {"key": "creative_status", "label": "创意状态", "category": "creative", "format": "text", "default": True, "level": ["creativity"], "aggregate": "skip"},
    {"key": "audit_status", "label": "审核状态", "category": "creative", "format": "text", "default": False, "level": ["creativity"], "aggregate": "skip"},
    {"key": "is_programmatic", "label": "创意类型", "category": "creative", "format": "text", "default": True, "level": ["creativity"], "aggregate": "skip"},
    {"key": "template_group_id", "label": "模板组ID", "category": "creative", "format": "text", "default": True, "level": ["creativity"], "aggregate": "skip"},
    {"key": "description", "label": "创意描述", "category": "creative", "format": "text", "default": False, "level": ["creativity"], "aggregate": "skip"},
    {"key": "ad_space_id", "label": "广告位ID", "category": "creative", "format": "text", "default": False, "level": ["creativity"], "aggregate": "skip"},
    {"key": "landing_page", "label": "落地页", "category": "creative", "format": "text", "default": False, "level": ["creativity"], "aggregate": "skip"},
    {"key": "creative_ctime", "label": "创意创建时间", "category": "creative", "format": "text", "default": False, "level": ["creativity"], "aggregate": "skip"},
    {"key": "creative_mtime", "label": "创意更新时间", "category": "creative", "format": "text", "default": False, "level": ["creativity"], "aggregate": "skip"},

    {"key": "show_count", "label": "展示量", "category": "basic", "format": "number", "default": True, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "click_count", "label": "点击量", "category": "basic", "format": "number", "default": True, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "charged_cost_milli", "label": "花费（元）", "category": "basic", "format": "money", "default": True, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "intelligent_charged_cost_milli", "label": "智能创意花费（元）", "category": "launch", "format": "money", "default": True, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},

    {"key": "san_lian_launch_total_consume", "label": "三连投放总消耗（元）", "category": "launch", "format": "money", "default": True, "level": ["account"], "aggregate": "sum"},
    {"key": "total_cash_consume", "label": "现金总消耗（元）", "category": "launch", "format": "money", "default": False, "level": ["account"], "aggregate": "sum"},
    {"key": "total_red_packet_consume", "label": "返货总消耗（元）", "category": "launch", "format": "money", "default": False, "level": ["account"], "aggregate": "sum"},
    {"key": "total_special_red_packet_consume", "label": "专项返货总消耗（元）", "category": "launch", "format": "money", "default": False, "level": ["account"], "aggregate": "sum"},
    {"key": "total_consume", "label": "整体实收总消耗（元）", "category": "launch", "format": "money", "default": False, "level": ["account"], "aggregate": "sum"},
    {"key": "click_rate", "label": "CTR", "category": "launch", "format": "percent", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "skip"},
    {"key": "cost_per_click", "label": "CPC", "category": "launch", "format": "money", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "skip"},
    {"key": "average_cost_per_thousand", "label": "ECPM", "category": "launch", "format": "money", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "skip"},

    {"key": "video_play_count", "label": "播放数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "video_like_count", "label": "点赞数", "category": "video", "format": "number", "default": True, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "video_fav_count", "label": "收藏数", "category": "video", "format": "number", "default": True, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "video_share_count", "label": "分享数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "video_bullet_count", "label": "弹幕数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "video_reply_count", "label": "评论数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "video_coin_count", "label": "投币数", "category": "video", "format": "number", "default": True, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "video_interact_count", "label": "互动数", "category": "video", "format": "number", "default": True, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "fan_increase_count", "label": "涨粉数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "account_subscribe_count", "label": "账号关注数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "comment_url_click_count", "label": "评论区组件点击数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "comment_url_show_count", "label": "评论区组件曝光数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "component_click_count", "label": "组件点击数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "dynamic_detail_browse_count", "label": "动态详情浏览数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "dynamic_goods_url_show_count", "label": "动态商品链接曝光数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "dynamic_goods_url_click_count", "label": "动态商品链接点击数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "live_bottom_icon_show_count", "label": "直播底部组件曝光数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "live_bottom_icon_click_count", "label": "直播底部组件点击数", "category": "video", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},

    {"key": "form_submit", "label": "表单提交数", "category": "clue", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "valid_leads", "label": "有效线索", "category": "clue", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "clue_valid_count", "label": "有效线索数", "category": "clue", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "phone_call_count", "label": "电话拨打数", "category": "clue", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "wechat_copy_count", "label": "微信复制数", "category": "clue", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},

    {"key": "app_download_count", "label": "下载数", "category": "app", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "download_success_count", "label": "下载完成数", "category": "app", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "app_active_count", "label": "激活数", "category": "app", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "app_register_count", "label": "注册数", "category": "app", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "app_pay_count", "label": "付费数", "category": "app", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},

    {"key": "order_place_count", "label": "下单数", "category": "ecommerce", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "order_pay_count", "label": "支付订单数", "category": "ecommerce", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "order_gmv", "label": "订单GMV", "category": "ecommerce", "format": "money", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "goods_view_count", "label": "商品浏览数", "category": "ecommerce", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "goods_add_cart_count", "label": "加购数", "category": "ecommerce", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},

    {"key": "live_entry_count", "label": "直播间进入数", "category": "live", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "live_watch_count", "label": "直播间观看数", "category": "live", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "live_follow_count", "label": "直播间关注数", "category": "live", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "live_comment_count", "label": "直播间评论数", "category": "live", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},

    {"key": "uv_num", "label": "UV", "category": "star", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "brand_ma_count", "label": "品牌MA数", "category": "grass", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "jinghuo_exposure_count", "label": "京火曝光数", "category": "jinghuo", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
    {"key": "jinghuo_click_count", "label": "京火点击数", "category": "jinghuo", "format": "number", "default": False, "level": ["account", "campaign", "unit", "creativity"], "aggregate": "sum"},
]

BILI_SPLIT_COLUMNS = [
    {"key": "date_time", "label": "小时"},
    {"key": "account_id", "label": "广告主账户ID"},
    {"key": "campaign_id", "label": "计划ID"},
    {"key": "unit_id", "label": "单元ID"},
    {"key": "creative_id", "label": "创意ID"},
]

BILI_REQUEST_FILTERS = [
    {"key": "campaign_id", "label": "计划ID"},
    {"key": "unit_id", "label": "单元ID"},
    {"key": "creative_id", "label": "创意ID"},
]
